######################################################################
# Automatically generated by qmake (2.00a) Thu Jul 13 14:09:22 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

LIBS+=-lglut -lGLU

QT += opengl


# Input
HEADERS += matrix.h mesh.h raytracing.h traqueboule.h Vec3D.h Vertex.h
SOURCES += main.cpp mesh.cpp raytracing.cpp
